### ISSUE TITLE
Handle hangout links for Chadev lunch talks

### ISSUE THREAD

**Issue by vendion** [chadev/Chadev_ircbot#24]
We should probably make Ash store the URL for the Google+ event page or YouTube Live stream for Dev Lunch talks.  There should also be a time attached to the URL to avoid Ash from giving a link to a previous talk.  The URLs will need to be set through IRC, may be limited to certain Nicks to limit trolling... not sure about that last part though.

## Setting live stream URL

To set the URL for a future talk:
```Ash devlunch url (date) (URL)```
example: ```Ash devlunch url 2015-02-26 http://youtube.com/...```
That would set the live stream URL for next weeks talk, as of 2015-02-19.

To set the URL for the day of the talk:
```Ash devlunch url today (URL)```
example: ```Ash devlunch url today http://youtube.com/...```
We could probably make the ```today``` bit optional and if only a URL is given then assume it is for today.

## Getting live stream URL

To get the URL for the lunch talk:
```Ash link to devlunch```

This has the ability to return different things depending on the situation.

### Asking for URL on a day that is not dev lunch day

Should return ```Sorry today is not dev lunch day.```

### Asking for URL when there is no URL or an expired URL set

Should return ```Sorry, I don't have a URL for today's live stream.  You can check if it is posted to the Meetup page at (Chadev meetup URL) or find it at our Google+ page at (Chadev G+ URL).```

### Asking for URL when there is a valid URL

Should return ```You can access the live stream for the talk here (live stream URL).```

Thoughts?  I know @kylegordy has been doing an awesome job posting the links to the live stream/video either before/after.  Would it be worth it to set the URL in advance and allow people to request it from Ash, this way the URL can be set a day or more in advance meaning one less things to worry about during setup for the talk.

Let the penny collecting start :moneybag:

**Comment by kylegordy** [comment]
@vendion Hmm… I like the idea of scheduling the hangout the day before. I'll just have to make sure I have a good reminder set :wink: I really like the direction you're headed. I mean why not right? It seems helpful to me :+1:

**Comment by vendion** [comment]
@kylegordy As for setting up the actual Hangout on Air, I don't mind helping out with that.  If it doesn't get setup in advance then that is why there is the option to just tell Ash "today".

If your for it then I will go ahead and remove the question label and will start on this feature.

**Comment by vendion** [comment]
Added in 1c50ceeeaaf6263060df998bd15828a6dd642e67
