### ISSUE TITLE
Move the help text out of Ash?

### ISSUE THREAD

**Issue by vendion** [chadev/Chadev_ircbot#25]
Currently when ```Ash help``` is ran the responses hits FreeNode's flood protection and so some things never actually make it to the channel.  Trying to figure out the magic number of milli/nano/seconds to wait between lines can be a PITA.  Another thing that having the help text be sent as separate messages does is possibly annoy users who have their client set to alert them when there is activity on the channel when their client is in the background.

To work around these issues, I propose that we move the help text out of Ash and into either a wiki page or a markdown file in the repo that Ash can link to.  If we go the markdown file route it can either be its own file or a section in the README.md that can be directly linked to.  I know that @keathley put a lot of effort into reworking how the help system currently works so help text is passed in the ```hear()``` function, making it easier to define new help items so I wouldn't want to make this change without running it passed you first.

**Comment by vendion** [comment]
There are also some aliases/variation on commands that Ash knows, but are not documented in the current help system.  These would probably be easier to address in an external document.

**Comment by StrangeWill** [comment]
(2:07:11 PM) StrangeWill: ash help
(2:07:12 PM) Ash_TheChadevBot: HAL Chadev IRC Edition build: 2015-02-19
(2:07:12 PM) StrangeWill: ash help
(2:07:12 PM) Ash_TheChadevBot: Supported commands:
(2:07:12 PM) Ash_TheChadevBot: chadevs all - List all members of Chadev
(2:07:12 PM) Ash_TheChadevBot: what is the next talk - Returns details on the next Chadev Lunch Talk
(2:07:12 PM) Ash_TheChadevBot: where's the party at? - Get the next event from the Chadev calendar
(2:07:13 PM) Ash_TheChadevBot: forget (key) - Tells Ash to forget something
(2:07:13 PM) StrangeWill: ash help
(2:07:13 PM) Ash_TheChadevBot: HAL Chadev IRC Edition build: 2015-02-19
(2:07:13 PM) Ash_TheChadevBot left the room (quit: Excess Flood).
(2:07:15 PM) StrangeWill: heh

**Comment by vendion** [comment]
Yeah that is yet another reason for moving it out of Ash and just linking to it.

**Comment by keathley** [comment]
The initial reasoning in moving help closer to the action was just so people would have an easier time remembering to update the help messages.  I'm worried that people wont remember to do it or that they'll get out of date.  Maybe that isn't a real problem.

If there is some way to get the help into pastebin or something like that (which would display correctly in irc for irccloud users at least) then that's what I would lean towards.  Otherwise the README or something similar is fine with me.

**Comment by vendion** [comment]
I can look into the pastebin option, is just pasting a link to a pastebin enough to trigger irccloud's displaying its content?  Also going that route it would need to have a clean fallback for non-irccloud users, the pastebin URLs are not very clear what it is so I wouldn't just want to return a link.  So the output would be something like ```you can find my usage here (URL)```.

In the mean time we can see if a second wait is enough to avoid issues in the next release.

**Comment by keathley** [comment]
Yeah IRCloud actually uses pastebin if you try to paste a long document or code.  I'm not sure if this is a great solution since it would only work for people paying for a service...I'll keep investigating

**Comment by vendion** [comment]
We will see what everyone thinks of just linking to the usage text when the help command is ran.  Pastebin also has some strict API limits for free accounts, so if Ash is unable to get confirmation on a successful paste, it falls back to linking to the Usage section of the README.  While this means that as features get added or changed the README needs to be updated as well, so far this has not been an issue, and except for a few minor differences in wording the README matches the help output.

**Comment by vendion** [comment]
This has been in testing for a week or so now and I have not heard any real complains about it, short of @StrangeWill  trolling but a different problem altogether.  Is this safe to assume being closed?

**Comment by keathley** [comment]
Seems good enough to me :+1:
